# Generated by Django 6.0.3 on 2026-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_assignee_task_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'created_at')},
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
