# Generated by Django 6.0.3 on 2026-03-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', 'assignee'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'project')},
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
